global using System.Runtime.CompilerServices;
global using Ardalis.SharedKernel;
global using Company.FirstTest.Core.ContributorAggregate;
global using Company.FirstTest.UseCases.Contributors.Create;
global using FluentAssertions;
global using MediatR;
global using Microsoft.Extensions.Logging;
global using NSubstitute;
global using Xunit;
